---
- name: Install and start Apache
  hosts: webservers
  become: true

  tasks:
  - name: Install Apache
    package:
      name: "{{ 'httpd' if ansible_distribution == 'Amazon' else 'apache2' }}"
      state: present

  - name: Ensure Apache is running and starting
    service:
      name: "{{ 'httpd' if ansible_distribution == 'Amazon' else 'apache2' }}"
      state: started
      enabled: true
